import type { ReactNode } from 'react';
import { Info, Sparkles, TriangleAlert } from 'lucide-react';

import { cn } from '../lib/cn';

/**
 * The disclaimer surface that must wrap or accompany every AI-generated output
 * in the product.
 *
 * This exists as a component rather than as copy-pasted markup for one reason:
 * a new page that renders AI output should not be able to omit the disclaimer
 * by accident. Reviewers can grep for `AIDisclaimer` next to any AI surface.
 *
 * The `variant` picks the wording. The wording is deliberately not overridable
 * as free text for the regulated variants — `valuation`, `legal` and `tax` carry
 * fixed language, because those are the ones that carry actual exposure. Use
 * `children` to add context *around* the fixed text, not to replace it.
 */

export type AIDisclaimerVariant =
  'general' | 'valuation' | 'legal' | 'tax' | 'market-context' | 'match';

type Tone = 'info' | 'warning';

interface DisclaimerCopy {
  label: string;
  body: string;
  tone: Tone;
}

const COPY: Record<AIDisclaimerVariant, DisclaimerCopy> = {
  general: {
    label: 'AI-generated',
    body:
      'This output was generated by an AI model and may be incomplete or inaccurate. ' +
      'It is provided for informational purposes only. Review it before relying on it.',
    tone: 'info',
  },
  valuation: {
    label: 'Estimate — not an appraisal',
    body:
      'This is an AI-generated estimate for discussion purposes only. It is not an appraisal, ' +
      'a fairness opinion, or a recommendation to buy or sell at any price. Valuation depends on ' +
      'facts not captured here, including diligence findings and deal structure. Engage a ' +
      'qualified valuation professional before acting.',
    tone: 'warning',
  },
  legal: {
    label: 'Not legal advice',
    body:
      'This platform does not provide legal advice and does not guarantee that any document or ' +
      'process meets your legal or regulatory obligations. Templates and checklists are tools to ' +
      'support your own compliance process. Consult a qualified attorney regarding your situation.',
    tone: 'warning',
  },
  tax: {
    label: 'Not tax advice',
    body:
      'This platform provides transaction records for your convenience and does not provide tax, ' +
      'legal, or accounting advice. You are solely responsible for your own tax obligations and ' +
      'should consult a qualified tax professional or accountant regarding your specific situation.',
    tone: 'warning',
  },
  'market-context': {
    label: 'Market context — not investment advice',
    body:
      'This is background market context assembled by an AI model from the sources and assumptions ' +
      'shown. It is not investment advice and is not a recommendation regarding any transaction. ' +
      'Verify figures independently before relying on them.',
    tone: 'info',
  },
  match: {
    label: 'AI-generated match',
    body:
      'Match scores are generated by an AI model from stated criteria and platform activity. ' +
      'They rank potential fit for your review — they are not an endorsement of any party or ' +
      'transaction, and not a substitute for your own diligence.',
    tone: 'info',
  },
};

const TONE_STYLES: Record<Tone, string> = {
  info: 'bg-info-subtle/60 border-info/25 text-text-secondary',
  warning: 'bg-warning-subtle/60 border-warning/30 text-text-secondary',
};

export interface AIDisclaimerProps {
  variant?: AIDisclaimerVariant;
  /** `inline` for a single dense line under a value; `block` for a full callout. */
  layout?: 'block' | 'inline';
  /** Extra context shown beneath the fixed disclaimer text. Never replaces it. */
  children?: ReactNode;
  className?: string;
}

export function AIDisclaimer({
  variant = 'general',
  layout = 'block',
  children,
  className,
}: AIDisclaimerProps) {
  const copy = COPY[variant];
  const Icon = copy.tone === 'warning' ? TriangleAlert : Info;

  if (layout === 'inline') {
    return (
      <p
        className={cn('text-text-muted flex items-start gap-1.5 text-xs', className)}
        data-ai-disclaimer={variant}
      >
        <Sparkles aria-hidden className="mt-0.5 h-3 w-3 shrink-0" />
        <span>
          <span className="text-text-secondary font-medium">{copy.label}.</span> {copy.body}
        </span>
      </p>
    );
  }

  return (
    <aside
      className={cn('flex gap-3 rounded-md border p-3 text-sm', TONE_STYLES[copy.tone], className)}
      data-ai-disclaimer={variant}
    >
      <Icon aria-hidden className="mt-0.5 h-4 w-4 shrink-0" />
      <div className="space-y-1">
        <p className="text-text-primary font-medium">{copy.label}</p>
        <p className="text-xs leading-relaxed">{copy.body}</p>
        {children ? <div className="pt-1 text-xs leading-relaxed">{children}</div> : null}
      </div>
    </aside>
  );
}

/** The exact tax-export wording, exported so non-React surfaces (PDF/CSV headers) reuse it. */
export const TAX_DISCLAIMER_TEXT = COPY.tax.body;
export const VALUATION_DISCLAIMER_TEXT = COPY.valuation.body;
