import { describe, expect, it } from 'vitest';

import { axisFor, compact, percentChange } from './scale';

describe('axisFor', () => {
  it('steps the axis on the 1/2/5 ladder', () => {
    /*
     * The bug this replaced, and the reason the check is on the *step*.
     *
     * Rounding the ceiling and then cutting it into a fixed number of ticks
     * gave 0 / 17 / 33 / 50 — a round top and gridlines nobody can read a bar
     * against. It was caught by rendering the chart and looking at it, which is
     * why this test exists at all.
     *
     * Asserting each tick "looks round" is circular: they are generated by
     * repeated addition, so they are always multiples of the step. The property
     * that actually matters is that the step itself is one of the numbers
     * people divide by without thinking.
     */
    for (const max of [1, 4, 5, 8, 14, 31, 37, 87, 207, 1001, 12_904]) {
      const { ticks } = axisFor(max);
      const step = (ticks[1] ?? 0) - (ticks[0] ?? 0);
      const magnitude = 10 ** Math.floor(Math.log10(step));
      const mantissa = Math.round((step / magnitude) * 1e6) / 1e6;

      expect([1, 2, 5], `axis for ${max} steps by ${step}`).toContain(mantissa);
    }
  });

  it('keeps gridlines whole when the data is whole', () => {
    // Half a view is not a thing. Every chart in this product plots a tally.
    for (const max of [1, 2, 3, 4, 7]) {
      for (const tick of axisFor(max).ticks) {
        expect(Number.isInteger(tick), `axis for ${max} has a tick at ${tick}`).toBe(true);
      }
    }
  });

  it('never draws a ceiling below the data', () => {
    // A ceiling under the maximum draws a bar out through the top of the plot.
    for (const max of [1, 3, 7, 19, 43, 87, 210, 999, 1001]) {
      expect(axisFor(max).ceiling, `ceiling for ${max}`).toBeGreaterThanOrEqual(max);
    }
  });

  it('starts at zero and ends at the ceiling', () => {
    const { ceiling, ticks } = axisFor(31);
    expect(ticks[0]).toBe(0);
    expect(ticks[ticks.length - 1]).toBe(ceiling);
  });

  it('keeps the gridline count readable', () => {
    // Two intervals makes a reader interpolate; eight is a grid with some bars
    // in it. Both ends are wrong, so both ends are asserted.
    for (const max of [1, 5, 14, 31, 207, 4321]) {
      const { ticks } = axisFor(max);
      expect(ticks.length, `axis for ${max} has ${ticks.length} ticks`).toBeGreaterThanOrEqual(2);
      expect(ticks.length, `axis for ${max} has ${ticks.length} ticks`).toBeLessThanOrEqual(7);
    }
  });

  it('gives an empty chart a height to divide by', () => {
    // The all-zeroes case, which is the state this product launches in.
    expect(axisFor(0)).toEqual({ ceiling: 1, ticks: [0, 1] });
    expect(axisFor(-5).ceiling).toBe(1);
    expect(axisFor(Number.NaN).ceiling).toBe(1);
  });

  it('does not leak a floating-point tail into a label', () => {
    // Fractional maxima only reach here from a non-count measure; the guard is
    // against binary floating point, which does not care what the data means.
    for (const max of [0.4, 1.2, 2.5]) {
      for (const tick of axisFor(max).ticks) {
        expect(String(tick).length, `tick ${tick}`).toBeLessThan(8);
      }
    }
  });
});

describe('compact', () => {
  it('keeps small counts exact and separated', () => {
    expect(compact(0)).toBe('0');
    expect(compact(1284)).toBe('1,284');
    expect(compact(9999)).toBe('9,999');
  });

  it('compacts once digits stop being read individually', () => {
    expect(compact(12_904)).toBe('12.9K');
    expect(compact(1_000_000)).toBe('1M');
    expect(compact(4_200_000)).toBe('4.2M');
  });

  it('drops a trailing zero decimal', () => {
    // "12.0K" reads as false precision.
    expect(compact(12_000)).toBe('12K');
  });

  it('does not print NaN at a person', () => {
    expect(compact(Number.NaN)).toBe('—');
  });
});

describe('percentChange', () => {
  it('refuses to divide by a zero baseline', () => {
    /*
     * The honest answer to "how much did it grow from nothing" is that the
     * question does not apply. Reporting an infinite rise, or quietly
     * substituting 100%, is the chart asserting something untrue — and on a
     * platform where the first week always starts at zero, it would be the
     * first thing every new seller saw.
     */
    expect(percentChange(4, 0)).toBeNull();
  });

  it('signs the direction', () => {
    expect(percentChange(150, 100)).toBe(50);
    expect(percentChange(50, 100)).toBe(-50);
  });
});
